config/routes.rb
Rails.application.routes.draw do

  resources :configs
  match '/check_projector' =>"requests#check_projector", :via => :post, :as => :chk_projector
match '/get_events' =>"index#get_events", :via => :post, :as => :get_events
match '/check_email' =>"requests#check_email", :via => :post, :as => :chk_email
match '/check_crossplatform' =>"requests#check_crossplatform", :via => :post, :as => :check_crossplatform
 match '/check_schedule' =>"requests#check_schedule", :via => :post, :as => :check_schedule
 match '/check_attendees' =>"requests#check_attendees", :via => :post, :as => :check_attendees
match '/check_schedule1' =>"requests#check_schedule1", :via => :post, :as => :check_schedule1
 

 # authenticated :users do
  #resources :requests, only: [:new, :status, :index, :show, :create, :edit, :update, :destroy]
  #end
#resources :requests, only: [:index, :show]
      devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'

      }
authenticated :user do
  root to: 'admin#index', as: :authenticated_root
end
  get 'requests/edit/', to: 'requests#edit'
  get 'admin/reschedule'
  get 'admin/approved'
  get 'admin/pending'
  get 'admin/index'
  get 'admin/manager'
  get 'admin/user'  
  get 'admin/list'

  get 'admin/setting'

  get 'index/dashboard'
  get 'test', to: 'index#test'
get 'requests/status/', to: 'requests#status', as: 'status'
 
  resources :rooms
  resources :staffs
  resources :requests
 # resources :users
  root to: 'index#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/configs/_form.html.erb
<%= form_for(config) do |f| %>
  <% if config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(config.errors.count, "error") %> prohibited this config from being saved:</h2>

      <ul>
      <% config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :p_custodian %>
    <%= f.text_field :p_custodian %>
  </div>

  <div class="field">
    <%= f.label :r_custodian %>
    <%= f.text_field :r_custodian %>
  </div>

  <div class="field">
    <%= f.label :projector %>
    <%= f.number_field :projector %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/configs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Configs</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>P custodian</th>
      <th>R custodian</th>
      <th>Projector</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @configs.each do |config| %>
      <tr>
        <td><%= config.company %></td>
        <td><%= config.p_custodian %></td>
        <td><%= config.r_custodian %></td>
        <td><%= config.projector %></td>
        <td><%= config.status %></td>
        <td><%= link_to 'Show', config %></td>
        <td><%= link_to 'Edit', edit_config_path(config) %></td>
        <td><%= link_to 'Destroy', config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Config', new_config_path %>

app/views/configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @config.company %>
</p>

<p>
  <strong>P custodian:</strong>
  <%= @config.p_custodian %>
</p>

<p>
  <strong>R custodian:</strong>
  <%= @config.r_custodian %>
</p>

<p>
  <strong>Projector:</strong>
  <%= @config.projector %>
</p>

<p>
  <strong>Status:</strong>
  <%= @config.status %>
</p>

<%= link_to 'Edit', edit_config_path(@config) %> |
<%= link_to 'Back', configs_path %>