config/routes.rb
Rails.application.routes.draw do

  resources :configs
  match '/check_projector' =>"requests#check_projector", :via => :post, :as => :chk_projector
match '/get_events' =>"index#get_events", :via => :post, :as => :get_events
match '/check_email' =>"requests#check_email", :via => :post, :as => :chk_email
match '/check_crossplatform' =>"requests#check_crossplatform", :via => :post, :as => :check_crossplatform
 match '/check_schedule' =>"requests#check_schedule", :via => :post, :as => :check_schedule
 match '/check_attendees' =>"requests#check_attendees", :via => :post, :as => :check_attendees
match '/check_schedule1' =>"requests#check_schedule1", :via => :post, :as => :check_schedule1
 

 # authenticated :users do
  #resources :requests, only: [:new, :status, :index, :show, :create, :edit, :update, :destroy]
  #end
#resources :requests, only: [:index, :show]
      devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'

      }
authenticated :user do
  root to: 'admin#index', as: :authenticated_root
end
  get 'requests/edit/', to: 'requests#edit'
  get 'admin/reschedule'
  get 'admin/approved'
  get 'admin/pending'
  get 'admin/index'
  get 'admin/manager'
  get 'admin/user'  
  get 'admin/list'

  get 'admin/setting'

  get 'index/dashboard'
  get 'test', to: 'index#test'
get 'requests/status/', to: 'requests#status', as: 'status'
 
  resources :rooms
  resources :staffs
  resources :requests
 # resources :users
  root to: 'index#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
    #before_filter :authenticate_user!, :only => [:destroy,  :index]
@cross_platform_error = nil
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

def status 
@request = Request.find(params[:id])
@all = Request.where("staff_id=?", @request.staff_id)
@staff = Staff.where("email=?", @request.email).first
@room = Room.where("id=?", @request.room_id).first
if params[:email] != @request.email
redirect_to index_dashboard_url, alert: 'Invalid Request Email, please enter email used to submit booking' 

else

  end

end 

  # GET /requests/1
  # GET /requests/1.json
  def show
      #:authenticate_user!
  end

  # GET /requests/new
  def new
  logged_in
  @request = Request.new
  @comp = 'all'

  end
def check_projector
   @date = Date.new params["date(1i)"].to_i, params["date(2i)"].to_i, params["date(3i)"].to_i
   @start = Time.new params["date(1i)"].to_i, params["date(2i)"].to_i, params["date(3i)"].to_i,params["startd(4i)"].to_i, params["startd(5i)"].to_i
   @end = Time.new params["date(1i)"].to_i, params["date(2i)"].to_i, params["date(3i)"].to_i,params["endd(4i)"].to_i, params["endd(5i)"].to_i
   return "true"
end 
  # GET /requests/1/edit
  def edit
  logged_in
  #@staff= Staff.joins(:requests).select("*").where(requests: {id: params[:id]}).first
  end

  # POST /requests
  # POST /requests.json
  def create
    @staff =  Staff.where("email= '#{params[:request][:email]}'")[0]
    #request.staff.id = @staff.id
      if @staff.nil?
        #redirect_back fallback_location: new_request_url
       redirect_to new_request_url, alert: "Email Record not found, contact Admin for registration"

         # request.staff.id = @staff.id
      elsif session[:cross_platform_error]
      redirect_to new_request_url, alert: "Company/location incorrect, contact Admin."
      elsif session[:date_error]
      redirect_to new_request_url, alert: "Room Booked, choose another date!"
      elsif session[:time_error]
      redirect_to new_request_url, alert: "Check meeting duration, adjust start/stop time!" 
      elsif  session[:attendees_error]     
        redirect_to new_request_url, alert: "Please check Attendees, should be greater than zero !!" 
      else
       sy=params[:request]["date(1i)"].to_i
        sm=params[:request]["date(2i)"].to_i
        sd=params[:request]["date(3i)"].to_i
        sh=params[:request]["startd(4i)"].to_i
        smin=params[:request]["startd(5i)"].to_i        
        ey=params[:request]["date(1i)"].to_i
        em=params[:request]["date(2i)"].to_i
        ed=params[:request]["date(3i)"].to_i
        eh=params[:request]["endd(4i)"].to_i
        emin=params[:request]["endd(5i)"].to_i        
  @request = Request.new(request_params)
@request.startd = Time.new sy,sm,sd,sh,smin
@request.endd = Time.new ey,em,ed,eh,emin
    respond_to do |format|
      if @request.save
        format.html { redirect_to index_dashboard_url, notice: 'Request was successfully created.'}
        format.json { render :show, status: :created, location: @request }
        RequestMailer.delay.newreq(@request)
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end  #end of respond format to save
        #end #cross platform check 
        end  #end check if staff is nil 
  end
  def check_crossplatform
    @email = current_user.email
    @room = Room.where("id= #{params[:room]}").first
      @staff =  Staff.where("email= ?", @email).first  
  if params[:act]!='reschedule'
      if !@staff.nil?
      if @staff.location == @room.location

        if @staff.company == @room.company
          @cross_platform_error = false
           session[:cross_platform_error] = false
        else
          if @staff.crossplatform 
            @cross_platform_error = false
             session[:cross_platform_error] = false
          else
            if @room.company == 'HQ' && @staff.priviledge == 1
              @cross_platform_error = false
              session[:cross_platform_error] = false
            else
            @cross_platform_error = true
            session[:cross_platform_error] = true
            end
          end
        end
      else
        if @staff.crossplatform 
            @cross_platform_error = false
             session[:cross_platform_error] = false
          else
            @cross_platform_error = true
            session[:cross_platform_error] = true
          end
      end   
    else
      #redirect_to new_request_url, alert: "Email cannot be empty!"

    end   #staff record must not be nil
  else
    @staff =  Staff.where("email= '#{params[:email]}'").first  
  end
  end 
  def check_email
    @f = Request.new
    @staff =  Staff.where("email= '#{params[:email]}'").first
    if !@staff.nil? 
         @comp = 'all'
             session[:email] = @staff.email
      email = @staff.email.split('@')[1].split('.')[0]
      if email == 'natural-prime'
        @comp = 'NPRNL'
      elsif email == 'esrnl'
        @comp == 'ESRNL'
      elsif email == 'primerafood-nigeria'
        @comp = 'PFNL'  
        end              
    else

    end

        respond_to do |format|
         format.js
      end 
  end
  def check_attendees
  @r = Room.where("id= #{params[:room_id]}").first
  att = params[:attendees].to_i
  @t = att
     if att >= 1
      session[:attendees_error]=false
        if att > @r.capacity
        @attendees_error = "Room capacity(#{@r.capacity}) exceeded, choose more convenient room. !"

        elsif att <= 6 && @r.capacity - att > 15
        @attendees_error = "Room capacity(#{@r.capacity}) under utilized, choose room with less capacity. !"
       end

    else
     @attendees_error =  "Please check Attendees, should be greater than zero !!"
    session[:attendees_error]=true

    end
end
    def check_schedule
   @date = Date.new params["date(1i)"].to_i, params["date(2i)"].to_i, params["date(3i)"].to_i
   @start = Time.new params["date(1i)"].to_i, params["date(2i)"].to_i, params["date(3i)"].to_i,params["startd(4i)"].to_i, params["startd(5i)"].to_i
   @end = Time.new params["date(1i)"].to_i, params["date(2i)"].to_i, params["date(3i)"].to_i,params["endd(4i)"].to_i, params["endd(5i)"].to_i
   # @date_error = Time.parse(params[:my_date]) 
   if @date >= Date.today || !Date.today.sunday? 


              @date_err = false
              session[:date_error] = false
               session[:time_error] = false
        if @start.hour<8 || @start.hour>17 || @end.hour<8 || @end.hour>17  #time should be within working hours
        @time_error = "Invalid time, not within working hours!"
        @time_err = true
        session[:time_error] = true
      else

            if @start.hour == @end.hour
                  if @end.min <= @start.min
                        @time_error = "Incorrect duration check time range!"
                         @time_err = true
                         session[:time_error] = true
                   elsif @end.min - @start.min < 10
                          @time_error = "Invalid duration, must be greater than 10 minutes!"
                          @time_err = true
                         session[:time_error] = true
                   end
           elsif @date == Date.today
                    if @start.hour < Time.now.hour
                     @time_error = "Invalid time, time past please correct!"
                    session[:time_error] = true
                   end
          elsif @start.hour > @end.hour
                     @time_error = "Invalid time, please correct end time!"
                    session[:time_error] = true          
            end #end date OK but same hour chosen 

       
           
        @res = Request.where("date= ? and room_id= ?", @date, params[:room_id])
        @time_err = false
        #session[:time_error] = false
        @res.each{ |f|
          if @start.hour.between?(f.startd.hour, f.endd.hour)
              @date_error = "Room scheduled, choose another time/room!"
              @time_err =true
              @date_err = true
              session[:date_error] = true
            if @start.hour==f.endd.hour
              if @start.min-f.endd.min <= 10
                @time_error = "Time conflict, Must start 10minute after Previous schedule!"
                  @time_err = true
                  session[:time_error] = @time_err
                else
              @time_error = ""
              @time_err = false
              session[:time_error] = false
              end
            else
              @date_error = "Room scheduled, choose another time/room!"
              @time_err = true
              @date_err = true
              session[:date_error] = true
            end

          elsif @end.hour.between?(f.startd.hour, f.endd.hour)
            @time_err=true
            session[:date_err] = @time_err
             @date_error = "Room scheduled, choose another time/room!"
    
          end
        }
      end  #Time within working hours and checking time conflicts
    else
                           @date_error = "Invalid date, must be today or greater"
                           @date_err = true
                          session[:date_error] = true
    end # end check if date past or invalid

  end
  def check_schedule1
  @date = Date.new params["date(1i)"].to_i, params["date(2i)"].to_i, params["date(3i)"].to_i
   @start = Time.new params["date(1i)"].to_i, params["date(2i)"].to_i, params["date(3i)"].to_i,params["startd(4i)"].to_i, params["startd(5i)"].to_i
   @end = Time.new params["date(1i)"].to_i, params["date(2i)"].to_i, params["date(3i)"].to_i,params["endd(4i)"].to_i, params["endd(5i)"].to_i
   # @date_error = Time.parse(params[:my_date]) 
   if @date >= Date.today
    @date_err = false
    session[:date_error] = false
    session[:time_error] = false

app/views/requests/_myform.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation" style="color: red;margin-left: 30%">
      <h3><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h3>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">    
<% state = "false" %>

    <div id="signupbox" style="  margin-top:2px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >
            <div class="panel-heading " >
                <div class="panel-title" >Create New Request </div>
            </div>  
            <div class="panel-body" >

                        <div id="div_id_select" class="form-group required">
                            <label for="id_select"  class="control-label col-md-4  requiredField">Title<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 "  style="margin-bottom: 10px">
                           <%= f.text_field(:title, style: 'margin-bottom: 10px', class:'input-md emailinput form-control') %>
                            </div>
                        </div> 
   

                         <div id="div_id_email" class="form-group required">
                            <label for="id_email" class="control-label col-md-4  requiredField"> Email<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 " style="margin-top: 5px; margin-bottom: 5px">
                               <% if user_signed_in?  %>
                           <%= f.text_field(:email, :value => @staff.email, style:'margin-bottom: 10px', class:'input-md emailinput form-control', data: {trigger: "blur"}, data: {required: "true" }, remote: true, id: 'email_box')%>
                           <% else %>
                              <%= f.text_field(:email, style:'margin-bottom: 10px', class:'input-md emailinput form-control',data: {trigger: "blur"}, data: {required: "true" }, remote: true, id: 'email_box')%>
                              <% end %>
                       <p id="email_error" style="display:none"> You are not eligible to request, contact Admin </p>
                            </div>     
                        </div> 
                    
                         <div id="div_id_email" class="form-group required">
                            <label for="id_email" class="control-label col-md-4  requiredField"> Request By<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 " style="margin-top: 5px; margin-bottom: 5px">
                            
                              <%= f.text_field(:requestby, :value => @staff.name, style:'margin-bottom: 10px', id: 'requester_name', class:'input-md emailinput form-control')%>

                            </div>     
                        </div>      



                        <div id="div_id_email" class="form-group required">
                            <label for="id_email" class="control-label col-md-4  requiredField"> Select Room<span class="asteriskField">*</span> </label>
                                    <div id="room_loc" class="controls col-md-8 " style="margin-top: 5px; margin-bottom: 5px">
                             <% if @staff.crossplatform %>
                              <%= f.collection_select(:room_id, Room.all, :id, :options_name, {},{class:'input-md emailinput form-control', style:'margin-bottom: 10px'})%>
                              <% elsif  @staff.location == 'IKOYI' %>
                              
                                    <%= f.collection_select(:room_id, Room.where("location= 'IKOYI'"), :id, :options_name, {},{class:'input-md emailinput form-control', style:'margin-bottom: 10px'})%>
                              <% else %>
                               <%= f.collection_select(:room_id, Room.where("company=?", @staff.company), :id, :options_name, {},{class:'input-md emailinput form-control', style:'margin-bottom: 10px'})%>
                          <% end %>
                          <p id="domain_error" style="display:none"> Error: Please choose room within company/location </p>
                            </div>   
                            <%# render partial: 'roomlist', locals: {f: f}  %>

                               <p id="domain_error" style="display:none"> Error: Please choose room within company/location </p>
                        </div> 
                        <%= f.hidden_field(:staff_id, {id: 'staff_id'}) %>

                        <div id="div_id_As" class="form-group required">
                            <label for="id_As"  class="control-label col-md-4  requiredField">Meeting Date<span class="asteriskField">*</span></label>
                            <div class="controls col-md-8 "  style="margin-bottom: 10px">
                              <%= f.date_select(:date, style:'margin-bottom: 10px',:order => [:day, :month, :year], :disabled => false, :html => {:class => "form-horizontal center"})%>
           <p id="date_error" style="display:none"> You are not eligible to request, contact Admin </p>

                            </div>
                        </div>

                        <div id="div_id_username" class="form-group required">
                            <label for="id_username" class="control-label col-md-4  requiredField"> Start time<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 col-md-pull-0">
                        <div class="input-md emailinput form-control " style="margin-bottom: 10px; border: 1px solid white" > 
                       <%= f.time_select(:startd, style:'margin-bottom: 10px',  :disabled => false, ignore_date: false)%> HH:MM
                          </div>
                                <p id="time_error" style="display:none">  </p>
                            </div>
                        </div>

                        <div id="div_id_email" class="form-group required">
                            <label for="id_email" class="control-label col-md-4  requiredField"> End time<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 ">
                         
                             <div class="input-md emailinput form-control" style="margin-bottom: 10px; border: 1px solid white" > 
          <%= f.time_select(:endd, style:'margin-bottom: 10px', :disabled => false, ignore_date: false)%> HH:MM
                     
                          </div>
                            </div>     
                        </div>
                         <div id="div_id_email" class="form-group required">
                            <label for="id_email" class="control-label col-md-4  requiredField"> Description<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 " style="margin-top: 5px; margin-bottom: 5px">
                            
                              <%= f.text_area(:desc, style:'margin-bottom: 10px', class:'input-md emailinput form-control')%>

                            </div>     
                        </div>   

  
                         <div id="div_id_email" class="form-group required">
                            <label for="id_email" class="control-label col-md-4  requiredField">Number of Attendees<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 " style="margin-top: 5px; margin-bottom: 5px">
                            
                              <%= f.number_field(:attendees, style:'margin-bottom: 20px',:remote => true, class:'input-md emailinput form-control')%>
                            <%= f.hidden_field :status, :value => 'booked' %>
                            <p id="attendees_error" style="display:none"> You are not eligible to request, contact Admin </p>
                            </div>     
                        </div> 


                         <div id="div_id_email" class="form-group required">
                            <label for="id_email" class="control-label col-md-4  requiredField"> Projector<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 " style="margin-top: 5px; margin-bottom: 5px">
                            
                              <%= f.check_box(:projector, style:'margin-bottom: 10px', class:'input-md emailinput form-control')%>

                            </div>     
                        </div>  

                         <div id="div_id_email" class="form-group required">
                            <label for="id_email" class="control-label col-md-4  requiredField"> Refreshment<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 " style="margin-top: 5px; margin-bottom: 5px">
                            
                              <%= f.check_box(:refreshment, style:'margin-bottom: 10px', class:'input-md emailinput form-control')%>

                            </div>     
                        </div>   

                         <div id="div_id_email" class="form-group required">
                            <label for="id_email" class="control-label col-md-4  requiredField"> Other requirements<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 " style="margin-top: 5px; margin-bottom: 5px">
                            
                              <%= f.text_area(:special, style:'margin-bottom: 10px', class:'input-md emailinput form-control')%>

                            </div>     
                        </div>   



                         <div id="div_id_email" class="form-group required">
                            
                            <div class="control-label col-md-4  requiredField" > <%= link_to 'Back', index_dashboard_path, class: 'btn btn-default' %>  </div>
                               
                            <div class="controls col-md-8 ">
                            <input type="submit" name="Signup" value="Book Now" class="btn btn-default" id="submit-id-signup" /> 
                           
                            </div>     
                        </div>     
      
            </div>
        </div>
    </div> 
</div>


<% end %>

app/views/requests/check_projector.js.erb
alert("projector");