config/routes.rb
Rails.application.routes.draw do

  resources :configs
  match '/check_projector' =>"requests#check_projector", :via => :post, :as => :chk_projector
match '/get_events' =>"index#get_events", :via => :post, :as => :get_events
match '/check_email' =>"requests#check_email", :via => :post, :as => :chk_email
match '/check_crossplatform' =>"requests#check_crossplatform", :via => :post, :as => :check_crossplatform
 match '/check_schedule' =>"requests#check_schedule", :via => :post, :as => :check_schedule
 match '/check_attendees' =>"requests#check_attendees", :via => :post, :as => :check_attendees
match '/check_schedule1' =>"requests#check_schedule1", :via => :post, :as => :check_schedule1
 

 # authenticated :users do
  #resources :requests, only: [:new, :status, :index, :show, :create, :edit, :update, :destroy]
  #end
#resources :requests, only: [:index, :show]
      devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'

      }
authenticated :user do
  root to: 'admin#index', as: :authenticated_root
end
  get 'requests/edit/', to: 'requests#edit'
  get 'admin/reschedule'
  get 'admin/approved'
  get 'admin/pending'
  get 'admin/index'
  get 'admin/manager'
  get 'admin/user'  
  get 'admin/list'

  get 'admin/setting'

  get 'index/dashboard'
  get 'test', to: 'index#test'
get 'requests/status/', to: 'requests#status', as: 'status'
 
  resources :rooms
  resources :staffs
  resources :requests
 # resources :users
  root to: 'index#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cmanager</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'styles', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'moment.min', 'data-turbolinks-track': 'reload' %>        
    <%= javascript_include_tag 'fullcalendar', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


  </head>

  <body>
      <header>
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header"><a class="navbar-brand visible-xs-block visible-sm-block visible-md-block visible-lg-block navbar-link" href="<%= index_dashboard_url %>"><b style="color:cyan">CONFERENCE ROOM</b>  MANAGEMENT SYSTEM </a>
                        <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                    </div>
                    <div class="collapse navbar-collapse" id="navcol-1">
                        <ul class="nav navbar-nav visible-xs-block visible-sm-block visible-md-block visible-lg-block visible-xs-inline visible-sm-inline navbar-right">
                           <li class="actove" role="presentation">
                           <% if user_signed_in? && current_user.admin? %>
                           <%= link_to "Manager", admin_manager_path  %>
                           <% elsif user_signed_in? && current_user.superadmin? %>
                           <%= link_to "Admin", admin_index_path  %>
                           <% elsif user_signed_in? && !current_user.admin? && !current_user.superadmin? %>
                           <%= link_to "User", admin_user_path  %>
                           <% end %>
                           </li>
                            <li class="active" role="presentation">

                            <%= link_to 'New Booking', new_request_url %></li>
                            <li class="active" role="presentation"><button type="button" class="btn btn-default btn-md" data-toggle="modal" data-target="#myModal">View Booking</button></li>
                            
                            <li role="presentation"> 
                              <% if user_signed_in? %>
                              <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
                              <% else %>
                               <%= link_to "Login", new_user_session_path  %>
                               <% end %>

                            </li>
                            <li role="presentation"><a href="#">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
             <p class="pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
  <% link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <% link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
  <% link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<div " class="alert <% if notice.nil? %><% else%> <%= 'alert-success' %>"><%end%> <h4 style="margin-left: 40%" id="notice"> <b><%= notice %></b></h4></div> 
<div class="alert <% if alert.nil? %><% else%> <%= 'alert-danger' %>"><%end%> <h5 style="margin-left: 40%" id="notice"> <b><%= alert %></b></h4></div> 

        </div>

    </header>
    <body>
    
    <!-- Notice and Alert -->   
    <%= yield %>
    
        <section id="sect1">
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h2 class="modal-title">Enter Booking Information</h2>
      </div>
      <div class="modal-body">
      <form method="get" action="<%= status_path %>" name="login_form">
             <label>Booking Number</label> <p><input type="text" class="span6" name="id" id="number" placeholder="Request Number"></p>
             <label>Booking Email</label> <p><input type="email" class="span6" name="email" placeholder="Your Email"></p>
              <p>
             
              <button type="submit" class="btn btn-default">Booking Status</button>
              </p>
            </form
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
    </section>


    <section id="sect1">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                <button class="btn btn-default btn-block btn-sm" >
                  Copyright -  NPRNL SOFTWARE DEVELOPMENT TEAM 
                </button>
                </div>
            </div>

        </div>
    </section>
  </body>
</html>